using Content.Client._Forge.DiscordAuth;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Shared.ContentPack;
using System.IO;

namespace Content.Client._RAT.Donation;

[GenerateTypedNameReferences]
public sealed partial class DonationPanel : Control
{
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly DiscordAuthManager _discord = default!;

    public DonationPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LoadText(InfoText, "/Credits/don-info.txt");
        LoadText(LevelsText, "/Credits/don-lvl.txt");
        LoadText(DiscordText, "/Credits/don-discord.txt");

        DonationTabs.SetTabTitle(0, "Информация");
        DonationTabs.SetTabTitle(1, "Уровни");
        DonationTabs.SetTabTitle(2, "Discord");

        var uri = IoCManager.Resolve<IUriOpener>();
        var donateUrl = "https://ss14.art"; 

        BuyButtonLevels.OnPressed += _ => uri.OpenUri(donateUrl);
        
        DiscordAuthButton.OnPressed += _ => uri.OpenUri(_discord.AuthLink);

        UpdateDiscordStatus();
    }

    private void LoadText(RichTextLabel label, string path)
    {
        if (!_resCache.ContentFileExists(path))
        {
            label.SetMessage(FormattedMessage.FromMarkup($"[color=red]Файл не найден: {path}[/color]"));
            return;
        }

        try 
        {
            using var stream = _resCache.ContentFileRead(path);
            using var reader = new StreamReader(stream);
            var rawContent = reader.ReadToEnd();
            
            var formatted = ParseSimpleMarkdown(rawContent);
            label.SetMessage(formatted);
        }
        catch (Exception e)
        {
            label.SetMessage(FormattedMessage.FromMarkup($"[color=orange]Ошибка чтения: {e.Message}[/color]"));
        }
    }

    private FormattedMessage ParseSimpleMarkdown(string text)
    {
        var processed = text
            .Replace("**", "[bold]")
            .Replace("# ", "[bold][font size=16]") 
            .Replace("\n", "[color=white]\n[/color]");

        return FormattedMessage.FromMarkup(processed);
    }

    public void UpdateDiscordStatus()
    {
        bool isLinked = string.IsNullOrEmpty(_discord.AuthLink);

        if (isLinked)
        {
            DiscordAuthButton.Visible = false;
            DiscordQr.Visible = false;
        }
        else
        {
            DiscordAuthButton.Visible = true;
            if (_discord.QrCodeTexture != null)
            {
                DiscordQr.Visible = true;
                DiscordQr.Texture = _discord.QrCodeTexture;
            }
        }
    }
}