- type: rank
  id: RatRankKnightSenior
  name: Магистр
  prefix: Магистр
  paygrade: K3

- type: rank
  id: RatRankKnightMiddle
  name: Баннерет
  prefix: Баннерет
  paygrade: K2

- type: rank
  id: RatRankKnightJunior
  name: Сир
  prefix: Сир
  paygrade: K1